version: '3.9'

services:
  api1: &api1
    hostname: api1
    build: ./api
    depends_on: 
      - db
    environment:
      PORT: 8080
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"
  
  api2:
    <<: *api1
    hostname: api2
    environment:
      PORT: 8080
    ports:
      - "8082:8080"

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"
    command: postgres -c max_connections=300

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"