FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

RUN apt-get update \
    && apt-get install unzip \
    && curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

WORKDIR /app

COPY rinha-2024-q1.csproj .
RUN dotnet restore

COPY . .

CMD ["dotnet", "watch", "run", "--project", "api/rinha-2024-q1.csproj"]